<?php

namespace pizzashop\tests\commande;

use Faker\Factory;
use PHPUnit\Framework\Attributes\DataProvider;
use pizzashop\shop\domain\entities\commande\Commande;
use pizzashop\shop\domain\entities\commande\Item;
use Illuminate\Database\Capsule\Manager as DB;

class ServiceCommandeTest extends \PHPUnit\Framework\TestCase {

    private static $commandeIds = [];
    private static $itemIds = [];
    private static $serviceProduits;
    private static $serviceCommande;
    private static $faker;// remplit la base de données avec des données de test

    //environ beaforeach ou before all 
    public static function setUpBeforeClass(): void
    {
        parent::setUpBeforeClass();
        $dbcom = __DIR__ . '/../../config/commande.db.test.ini';
        $dbcat = __DIR__ . '/../../config/catalog.db.ini';
        $db = new DB();
        echo('coucou'.$dbcom);
        $db->addConnection(parse_ini_file($dbcom), 'commande');
        $db->addConnection(parse_ini_file($dbcat), 'catalog');
        $db->setAsGlobal();
        $db->bootEloquent();

        self::$serviceProduits = new \pizzashop\shop\domain\service\catalogue\ServiceCatalogue();
        self::$serviceCommande = new \pizzashop\shop\domain\service\commande\ServiceCommande(self::$serviceProduits);
        self::$faker = Factory::create('fr_FR');
        self::fill();

    }

    public static function tearDownAfterClass(): void
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
        self::cleanDB();
    }


    private static function cleanDB(){
        foreach (self::$commandeIds as $id){
            Commande::find($id)->delete();
        }
        foreach (self::$itemIds as $id){
            Item::find($id)->delete();
        }
    }
    private static function fill() {
   	 	// TODO : créer une commande dans la base pour tester l'accès à une commande
            $commande = Commande::create([
                'id' => self::$faker->uuid,
                'date_commande' => self::$faker->dateTimeBetween('-3 year', 'now')->format('Y-m-d H:i:s'),
                'type_livraison' => Commande::LIVRAISON_DOMICILE,
                'mail_client' => self::$faker->email,
                'etat' => Commande::ETAT_CREE
            ]);
        echo $commande->id_commande;
        echo ("coucou");
        self::$commandeIds[] = $commande->id_commande;
        // TODO : créer des items dans la base pour tester l'accès à une commande
        //$item = new Item();
        //$item->id_item = self::$faker->uuid;
        //$item->numero = self::$faker->randomDigit;
        //$item->taille = self::$faker->randomElement(['petite', 'moyenne', 'grande']);
        //$item->quantite = self::$faker->randomDigit;
        //$item->id_commande = $commande->id_commande;
        //$item->save();
        //self::$itemIds[] = $item->id_item;
    }


    public function testAccederCommande(){
        //$id = self::$commandeIds[0];
        foreach (self::$commandeIds as $id){
            $commandeEntity = Commande::find($id);
            $commandeDTO = self::$serviceCommande->accederCommande($id);
            $this->assertNotNull($commandeDTO);
 
            // TODO : comparer les données de l'entité et du DTO
        }
    }

}